// Auto-generated by parallel_unsplash_photos_search
// Do not edit manually

export const IMAGES = {
  CARD_BG_1: "https://images.unsplash.com/photo-1511140973288-19bf21d7e771?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHwyfHxwbGF5aW5nJTIwY2FyZHMlMjBnYW1lJTIwZGFyayUyMGJhY2tncm91bmR8ZW58MHwwfHx8MTc3MjcyNjIxNnww&ixlib=rb-4.1.0&q=80&w=1080",
  CARD_BG_2: "https://images.unsplash.com/photo-1525468617831-166cad925bf5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHwxfHxwbGF5aW5nJTIwY2FyZHMlMjBnYW1lJTIwZGFyayUyMGJhY2tncm91bmR8ZW58MHwwfHx8MTc3MjcyNjIxNnww&ixlib=rb-4.1.0&q=80&w=1080",
  CARD_BG_3: "https://images.unsplash.com/photo-1651174061616-c441266524f3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHwzfHxwbGF5aW5nJTIwY2FyZHMlMjBnYW1lJTIwZGFyayUyMGJhY2tncm91bmR8ZW58MHwwfHx8MTc3MjcyNjIxNnww&ixlib=rb-4.1.0&q=80&w=1080",
  MOBILE_UI_1: "https://images.unsplash.com/photo-1607114284218-284c590fcb23?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHw0fHxtb2JpbGUlMjBnYW1pbmclMjBpbnRlcmZhY2UlMjBkYXJrfGVufDB8MXx8fDE3NzI3MjYyMTd8MA&ixlib=rb-4.1.0&q=80&w=1080",
  MOBILE_UI_2: "https://images.unsplash.com/photo-1634743556192-d19f0c69ff3a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHw3fHxtb2JpbGUlMjBnYW1pbmclMjBpbnRlcmZhY2UlMjBkYXJrfGVufDB8MXx8fDE3NzI3MjYyMTd8MA&ixlib=rb-4.1.0&q=80&w=1080",
  MOBILE_UI_3: "https://images.unsplash.com/photo-1643336177967-710676ec3fa7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHwzfHxtb2JpbGUlMjBnYW1pbmclMjBpbnRlcmZhY2UlMjBkYXJrfGVufDB8MXx8fDE3NzI3MjYyMTd8MA&ixlib=rb-4.1.0&q=80&w=1080",
  MOBILE_UI_4: "https://images.unsplash.com/photo-1616578981448-9e9d74efe3c8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHw1fHxtb2JpbGUlMjBnYW1pbmclMjBpbnRlcmZhY2UlMjBkYXJrfGVufDB8MXx8fDE3NzI3MjYyMTd8MA&ixlib=rb-4.1.0&q=80&w=1080",
  MOBILE_UI_5: "https://images.unsplash.com/photo-1621345102286-6fe2ddfdbd55?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHw2fHxtb2JpbGUlMjBnYW1pbmclMjBpbnRlcmZhY2UlMjBkYXJrfGVufDB8MXx8fDE3NzI3MjYyMTd8MA&ixlib=rb-4.1.0&q=80&w=1080",
  MOBILE_UI_6: "https://images.unsplash.com/photo-1663153203126-08bbadc178ad?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHwyfHxtb2JpbGUlMjBnYW1pbmclMjBpbnRlcmZhY2UlMjBkYXJrfGVufDB8MXx8fDE3NzI3MjYyMTd8MA&ixlib=rb-4.1.0&q=80&w=1080",
  MOBILE_UI_7: "https://images.unsplash.com/photo-1653772470643-ef100551c192?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHwxfHxtb2JpbGUlMjBnYW1pbmclMjBpbnRlcmZhY2UlMjBkYXJrfGVufDB8MXx8fDE3NzI3MjYyMTd8MA&ixlib=rb-4.1.0&q=80&w=1080",
  MOBILE_UI_8: "https://images.unsplash.com/photo-1762681829945-c260685037de?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHw4fHxtb2JpbGUlMjBnYW1pbmclMjBpbnRlcmZhY2UlMjBkYXJrfGVufDB8MXx8fDE3NzI3MjYyMTd8MA&ixlib=rb-4.1.0&q=80&w=1080",
  QR_SCAN_1: "https://images.unsplash.com/photo-1586374579268-e08642454549?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHw1fHxRUiUyMGNvZGUlMjBzY2FubmluZyUyMG1vYmlsZSUyMHBob25lfGVufDB8MXx8fDE3NzI3MjYyMTZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  QR_SCAN_2: "https://images.unsplash.com/photo-1605513524042-426bace35fc9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHwxfHxRUiUyMGNvZGUlMjBzY2FubmluZyUyMG1vYmlsZSUyMHBob25lfGVufDB8MXx8fDE3NzI3MjYyMTZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  QR_SCAN_3: "https://images.unsplash.com/photo-1650304003871-2bdb8aa62dfc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHw3fHxRUiUyMGNvZGUlMjBzY2FubmluZyUyMG1vYmlsZSUyMHBob25lfGVufDB8MXx8fDE3NzI3MjYyMTZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  QR_SCAN_4: "https://images.unsplash.com/photo-1578317260099-6021237c3391?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHw2fHxRUiUyMGNvZGUlMjBzY2FubmluZyUyMG1vYmlsZSUyMHBob25lfGVufDB8MXx8fDE3NzI3MjYyMTZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  QR_SCAN_5: "https://images.unsplash.com/photo-1746016988324-840f3f184191?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHwyfHxRUiUyMGNvZGUlMjBzY2FubmluZyUyMG1vYmlsZSUyMHBob25lfGVufDB8MXx8fDE3NzI3MjYyMTZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  QR_SCAN_6: "https://images.unsplash.com/photo-1625465329894-9cfaf8a63332?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHw0fHxRUiUyMGNvZGUlMjBzY2FubmluZyUyMG1vYmlsZSUyMHBob25lfGVufDB8MXx8fDE3NzI3MjYyMTZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  QR_SCAN_7: "https://images.unsplash.com/photo-1738641928045-d423f8b9b243?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHw4fHxRUiUyMGNvZGUlMjBzY2FubmluZyUyMG1vYmlsZSUyMHBob25lfGVufDB8MXx8fDE3NzI3MjYyMTZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  QR_SCAN_8: "https://images.unsplash.com/photo-1758543102397-e14b5dfdd8bd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHwzfHxRUiUyMGNvZGUlMjBzY2FubmluZyUyMG1vYmlsZSUyMHBob25lfGVufDB8MXx8fDE3NzI3MjYyMTZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
} as const;

export type ImageKey = keyof typeof IMAGES;
